#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -e

if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

# Function to display help
help_function() {
    cat <<EOF

Usage: $(basename "$0") [-h]

Options:
  -h, --help       Display this help message and exit

EOF
}

# Function to check if a command exists
command_exists() {
    type "$1" &> /dev/null
}

# Check required dependencies
check_dependencies() {
    if ! command_exists docker; then
        cat <<EOF

Docker is not installed. Install it using:

curl -fsSL https://get.docker.com -o get-docker.sh && \\
    sudo sh get-docker.sh

EOF
        exit 1
    fi
}

# Main function of the script
main() {

    # Parse arguments
    while [[ "$#" -gt 0 ]]; do
        case "$1" in
            -h|--help)
                help_function
                exit 0
                ;;
            *)
                echo "Unknown parameter passed: $1"
                help_function
                exit 1
                ;;
        esac
    done

    check_dependencies && \
        mkdir -p {ollama,autogenstudio} && \
        sudo docker compose \
        up --build && \
        sudo docker exec devcontainer-ollama-1 \
        ollama pull phi3
}

main "$@"
